# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - sbt compile
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ee0faf7d8f12bfe35fb7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false
# Use container-based infrastructure
sudo: false
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
